# Generated by Django 4.1.3 on 2022-11-18 10:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('whatsappbot', '0001_initial'),
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=40, null=True, verbose_name='Phone Number')),
                ('pin', models.CharField(max_length=20, verbose_name='Pin')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=('F', 'Female'), max_length=1, verbose_name='Gender')),
                ('Account_balance', models.FloatField(default=0.0, null=True, verbose_name='Account Balance')),
                ('Account_number', models.CharField(max_length=10, null=True, unique=True)),
                ('registered_telegram', models.BooleanField(default=False, null=True)),
                ('registered_whatsapp', models.BooleanField(default=False, null=True)),
                ('user_network', models.CharField(choices=[('mtn', 'MTN'), ('orange', 'ORANGE')], default=('mtn', 'MTN'), max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('telegram_transactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_trans', to='telegrambot.transactionhistory')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('whatsapp_transactions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_trans', to='whatsappbot.transactionhistory')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
