# Generated by Django 4.1.3 on 2022-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='688999888', max_length=20, primary_key=True, serialize=False, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
