# Generated by Django 4.1.3 on 2022-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('transaction_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, null=True)),
                ('from_number', models.CharField(max_length=20, null=True)),
                ('to_number', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('transaction_type', models.CharField(choices=[('pay_fees', 'Pay Fees'), ('send_money', 'send Money'), ('cashin', 'Cashin'), ('Cashout', 'Cashout')], default=None, max_length=20)),
            ],
        ),
    ]
